// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebReport78.Models;

public partial class Department
{
    public int IdDept { get; set; }

    public int? IdOrg { get; set; }

    public string Name { get; set; }

    public string Code { get; set; }

    public string Address { get; set; }

    public string Description { get; set; }

    public short? OrderNo { get; set; }

    public DateTime? DateCreated { get; set; }

    public virtual Organization IdOrgNavigation { get; set; }

    public virtual ICollection<Staff> Staff { get; set; } = new List<Staff>();
}