// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebReport78.Models;

public partial class Organization
{
    public int IdOrg { get; set; }

    public string Name { get; set; }

    public string Code { get; set; }

    public string Website { get; set; }

    public string Address { get; set; }

    public string Description { get; set; }

    public byte? StartFloor { get; set; }

    public byte? EndFloor { get; set; }

    public short? OrderNo { get; set; }

    public DateTime? DateCreated { get; set; }

    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    public virtual ICollection<Staff> Staff { get; set; } = new List<Staff>();
}