// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebReport78.Model2s;

public partial class TblGatewayMember
{
    public int Id { get; set; }

    public string IdApp { get; set; }

    public string IdLocation { get; set; }

    /// <summary>
    /// Default: User email
    /// </summary>
    public string IdMember { get; set; }

    /// <summary>
    /// - Super Admin
    /// - Admin
    /// - Member
    /// - Temporary Admin
    /// - Temporary Member
    /// </summary>
    public string IdRole { get; set; }

    public long? StartTime { get; set; }

    public long? EndTime { get; set; }

    public string UserAgent { get; set; }

    public string ContentLanguage { get; set; }

    public virtual TblGateway IdLocationNavigation { get; set; }
}