// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebReport78.Model2s;

public partial class TblGateway
{
    public int Id { get; set; }

    public string Guid { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string PublicKey { get; set; }

    public string SharedKey { get; set; }

    public string HomeConfig { get; set; }

    public string UserAgent { get; set; }

    public string ContentLanguage { get; set; }

    public long? DateCreated { get; set; }

    public virtual ICollection<TblGatewayMember> TblGatewayMembers { get; set; } = new List<TblGatewayMember>();
}