// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebReport78.Model2s;

public partial class TblSsoUser
{
    public int Id { get; set; }

    public string DisplayName { get; set; }

    public string Email { get; set; }

    public string Mobile { get; set; }

    public string Password { get; set; }

    public string Salt { get; set; }

    public byte Status { get; set; }

    public int? DateCreated { get; set; }
}